In [85]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import KFold
from sklearn.metrics import confusion_matrix
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import f1_score

In [54]:
df = pd.read_csv('naive-db.csv')
cols = ['Amplitude', 'Std', 'PeriodLS', 'Mean', 'MaxSlope', 'Meanvariance', 'LinearTrend']
X = df[cols]
y = df[['label']]

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [15]:
regr = RandomForestRegressor(max_depth=4, random_state=0,n_estimators=100)

In [18]:
regr.fit(X_train, y_train)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=4,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_split=1e-07, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           n_estimators=100, n_jobs=1, oob_score=False, random_state=0,
           verbose=0, warm_start=False)

In [21]:
y_predicted = regr.predict(X_test)

In [60]:
y_predicted

array([ 2.46745495,  0.74941814,  0.74941814, ...,  3.7245449 ,
        4.76161696,  2.77230078])

In [102]:
kf = KFold(n_splits=10, shuffle=True)
kf.get_n_splits(X)

10

In [67]:
print(kf)

KFold(n_splits=10, random_state=None, shuffle=True)


In [105]:
regr = RandomForestClassifier(max_depth=4, random_state=0,n_estimators=100)
y_predicted = []
indexes = []
for train, test in kf.split(df):
    indexes += [*test]
    regr.fit(X.loc[train], y.loc[train,'label'])
    y_predicted += [*regr.predict(X.loc[test,cols])]
    

print(y.loc[indexes,'label'])
print(confusion_matrix(y.loc[indexes,'label'], y_predicted))
    

6        0
14       0
15       0
19       0
35       0
42       0
49       0
50       0
60       0
67       0
74       0
81       0
112      0
120      0
132      0
134      0
140      0
143      0
144      0
145      0
159      0
160      0
163      0
169      0
184      0
185      0
215      0
219      0
240      0
242      0
        ..
59751    6
59753    6
59756    6
59761    6
59764    6
59786    6
59797    6
59813    6
59842    6
59855    6
59883    6
59889    6
59894    6
59898    6
59903    6
59905    6
59910    6
59920    6
59931    6
59943    6
59947    6
59959    6
59962    6
59967    6
59977    6
59986    6
60025    6
60026    6
60027    6
60069    6
Name: label, dtype: int64
[[7299    6  311 1590  604  190    0]
 [   5 8237    0    1    0   94    0]
 [  63    2 8943    0    0  992    0]
 [ 611    3   11 9331   37    7    0]
 [ 222    0   13  128 9504  133    0]
 [  48  223  174    5    2 9548    0]
 [ 893    1  200  215  236  195    0]]


In [96]:
recall_score(y.loc[indexes,'label'], y_predicted, average='macro')

0.77862643808152987

In [97]:
precision_score(y.loc[indexes,'label'], y_predicted, average='macro') 

/Users/EnriqueOlivares/anaconda/lib/python3.6/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


0.75653900863527113

In [86]:
f1_score(y.loc[indexes,'label'], y_predicted, average='macro') 

/Users/EnriqueOlivares/anaconda/lib/python3.6/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


0.76668867516024941

In [93]:
X

Amplitude       Std   PeriodLS       Mean    MaxSlope  Meanvariance  \
0        0.53300  0.283701   1.089524  19.338182    7.039598      0.014671   
1        0.27150  0.127947   3.209689  19.586202   10.640067      0.006533   
2        0.30150  0.138996   2.268446  19.913902   21.778886      0.006980   
3        0.16400  0.095606   1.561432  15.151209    0.353493      0.006310   
4        0.11125  0.056008   1.166648  18.361809   17.002882      0.003050   
5        0.15350  0.067260   1.151584  18.312716    0.338084      0.003673   
6        0.05700  0.026069   2.218157  16.997020    0.141941      0.001534   
7        0.07525  0.040618   0.554437  17.994407   10.086455      0.002257   
8        0.18050  0.070647   0.905880  16.649661    0.428307      0.004243   
9        0.15950  0.078124   1.124337  19.313842    3.740648      0.004045   
10       0.09900  0.048697   0.098774  18.679498    2.940285      0.002607   
11       0.29725  0.136695   1.242079  19.217322    6.628242      0.007113   
12       0.10575  0.053227   0.618381  17.781985    8.923513      0.002993   
13       0.34300  0.177989   0.811202  19.599110   27.053140      0.009081   
14       0.30600  0.156720   1.405782  18.388992    5.924951      0.008522   
15       0.36400  0.161571   1.436012  18.817746   19.402985      0.008586   
16       0.35900  0.176978   0.478968  20.061341   97.417840      0.008822   
17       0.22750  0.128184   1.080266  17.255148    4.518558      0.007429   
18       0.35650  0.177436   1.198409  19.791563   19.936102      0.008965   
19       0.06050  0.028792  19.330375  17.473465    1.943574      0.001648   
20       0.08800  0.046644   0.670545  18.305855    8.582090      0.002548   
21       0.25775  0.125681   0.445676  19.772533   28.818444      0.006356   
22       0.07050  0.037058   0.067044  18.082049    3.173749      0.002049   
23       0.08575  0.050265   0.525417  16.907175    0.627328      0.002973   
24       0.15050  0.068045   0.927693  18.386325    0.358355      0.003701   
25       0.03200  0.015149  26.263715  16.685500    1.250823      0.000908   
26       0.05650  0.028522   2.215634  18.012918    3.926097      0.001583   
27       0.54275  0.253969   1.889951  19.828372    1.404319      0.012808   
28       0.04100  0.018375   3.445814  17.129442    0.155176      0.001073   
29       0.12650  0.062898   1.784742  18.770518   35.820896      0.003351   
...          ...       ...        ...        ...         ...           ...   
60047    0.25650  0.125684   0.388143  19.215777   60.836502      0.006541   
60048    0.28300  0.131474   1.047511  14.281704    9.147425      0.009206   
60049    0.14150  0.062361   1.065292  16.301671   10.460993      0.003825   
60050    0.08300  0.037653   2.053885  15.723816   10.757946      0.002395   
60051    0.03150  0.012981   2.188230  15.475905   11.963190      0.000839   
60052    0.07250  0.034307   0.455289  17.507321   10.844444      0.001960   
60053    0.04625  0.022848   0.670305  16.818212   11.042945      0.001359   
60054    0.05000  0.024760   0.261902  15.593186    7.228916      0.001588   
60055    0.07350  0.035042   0.982487  15.974130    4.317181      0.002194   
60056    0.21250  0.117050   1.004458  17.818238   16.160714      0.006569   
60057    0.19725  0.100044   0.190143  17.426027   29.674419      0.005741   
60058    0.01950  0.010394   1.038639  14.396260    2.573203      0.000722   
60059    0.22500  0.118035   0.372763  16.971621   14.220183      0.006955   
60060    0.17225  0.082835   1.024174  16.627902   11.438785      0.004982   
60061    0.37950  0.179469   0.322735  18.952080   44.729606      0.009470   
60062    0.04750  0.025954   1.941933  16.463493    6.819716      0.001576   
60063    0.18450  0.088164   0.922872  18.247729   13.272011      0.004832   
60064    0.01700  0.008142   1.388315  15.100240    4.424779      0.000539   
60065    0.27325  0.124852   2.282180  16.790902   14.109347      0.007436   
60066    0.32625  0.155843   